apiVersion: apps/v1
kind: Deployment
metadata:
  name: train
spec:
  selector:
    matchLabels:
      app: train
  replicas: 1
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
      - name: train
        image: prasanth8125/togo
        ports:
        - containerPort: 80
